package com.SoftEngUniNA.CineMates20Desktop.views;

import com.SoftEngUniNA.CineMates20Desktop.controllers.StatsPageController;
import java.awt.CardLayout;
import java.awt.Color;
import static java.lang.Thread.sleep;
import java.util.List;
import java.util.*;
import java.util.logging.Level;
import java.util.logging.Logger;


public class MainPage extends javax.swing.JFrame {
    private String logged_operator;
    private final float[] showed_stats=new float[9];
    private final CardLayout card_layout;
    private final javax.swing.JLabel[] stats_labels=new javax.swing.JLabel[9];
    private boolean recovered_stats=false;
    StatsPageController controller=new StatsPageController(this);
    
    public MainPage() {
        initComponents();
        homePnl.setBackground(Color.darkGray);
        card_layout=(CardLayout)(PnlCards.getLayout()); 
    }
    
    public MainPage(String op_username) {
        initComponents();
        logged_operator=op_username;
        logged_operator_label.setText(logged_operator);
        homePnl.setBackground(Color.darkGray);
        card_layout=(CardLayout)(PnlCards.getLayout()); 
        stats_labels[0]=accesses_lbl;
        stats_labels[1]=ext_prov_users_lbl;
        stats_labels[2]=email_users_lbl;
        stats_labels[3]=user_searches_lbl;
        stats_labels[4]=movie_searches_lbl;
        stats_labels[5]=review_lbl;
        stats_labels[6]=avg_review_lbl;
        stats_labels[7]=list_lbl;
        stats_labels[8]=avg_movie_lbl;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        PnlCards = new javax.swing.JPanel();
        HomePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        StatsPanel = new javax.swing.JPanel();
        ext_prov_pnl = new javax.swing.JPanel();
        ext_prov_users_lbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        email_pnl = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        email_users_lbl = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        avg_review_pnl = new javax.swing.JPanel();
        avg_review_lbl = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        users_searces_pnl = new javax.swing.JPanel();
        user_searches_lbl = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        review_pnl = new javax.swing.JPanel();
        review_lbl = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        movie_searches_pnl = new javax.swing.JPanel();
        movie_searches_lbl = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        accesses_pnl = new javax.swing.JPanel();
        accesses_lbl = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        avg_movie_pnl = new javax.swing.JPanel();
        avg_movie_lbl = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        list_panel = new javax.swing.JPanel();
        list_lbl = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        NavigationBarMenu = new javax.swing.JPanel();
        CineMatesTitle = new javax.swing.JLabel();
        logged_operator_label = new javax.swing.JLabel();
        homePnl = new javax.swing.JPanel();
        home_icon = new javax.swing.JLabel();
        home_lbl = new javax.swing.JLabel();
        statsPnl = new javax.swing.JPanel();
        stats_lbl = new javax.swing.JLabel();
        stats_icon = new javax.swing.JLabel();
        logoutPnl = new javax.swing.JPanel();
        logout_lbl = new javax.swing.JLabel();
        logout_icon = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CineMates20 Desktop v.1.0 ©");
        setBackground(new java.awt.Color(0, 0, 0));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/images/official_logo_icon.png")).getImage());
        setLocation(new java.awt.Point(50, 50));
        setMaximumSize(new java.awt.Dimension(1200, 720));
        setMinimumSize(new java.awt.Dimension(1200, 720));
        setPreferredSize(new java.awt.Dimension(1200, 720));
        setResizable(false);
        setSize(new java.awt.Dimension(1280, 720));

        jSplitPane1.setBackground(new java.awt.Color(0, 0, 0));
        jSplitPane1.setDividerSize(0);
        jSplitPane1.setForeground(new java.awt.Color(0, 0, 0));
        jSplitPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jSplitPane1.setEnabled(false);
        jSplitPane1.setMaximumSize(new java.awt.Dimension(1280, 720));
        jSplitPane1.setMinimumSize(new java.awt.Dimension(1280, 720));
        jSplitPane1.setPreferredSize(new java.awt.Dimension(1280, 720));

        PnlCards.setForeground(new java.awt.Color(255, 255, 255));
        PnlCards.setMaximumSize(new java.awt.Dimension(1200, 720));
        PnlCards.setPreferredSize(new java.awt.Dimension(1200, 720));
        PnlCards.setLayout(new java.awt.CardLayout());

        HomePanel.setBackground(new java.awt.Color(204, 204, 204));
        HomePanel.setMaximumSize(new java.awt.Dimension(1200, 720));
        HomePanel.setMinimumSize(new java.awt.Dimension(1200, 720));
        HomePanel.setPreferredSize(new java.awt.Dimension(1200, 720));

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Istruzioni:");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1009, Short.MAX_VALUE))
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(165, 165, 165)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(336, Short.MAX_VALUE))
        );

        PnlCards.add(HomePanel, "HomePanel");

        StatsPanel.setBackground(new java.awt.Color(102, 102, 102));
        StatsPanel.setMaximumSize(new java.awt.Dimension(1200, 720));
        StatsPanel.setMinimumSize(new java.awt.Dimension(1200, 720));
        StatsPanel.setPreferredSize(new java.awt.Dimension(1200, 720));

        ext_prov_pnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ext_prov_pnl.setMaximumSize(new java.awt.Dimension(350, 80));
        ext_prov_pnl.setMinimumSize(new java.awt.Dimension(350, 80));
        ext_prov_pnl.setPreferredSize(new java.awt.Dimension(350, 80));

        ext_prov_users_lbl.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 15)); // NOI18N
        ext_prov_users_lbl.setText("caricamento...");

        jLabel3.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel3.setText("Utenti registrati con provider esterno");

        javax.swing.GroupLayout ext_prov_pnlLayout = new javax.swing.GroupLayout(ext_prov_pnl);
        ext_prov_pnl.setLayout(ext_prov_pnlLayout);
        ext_prov_pnlLayout.setHorizontalGroup(
            ext_prov_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ext_prov_pnlLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(18, 18, 18))
            .addGroup(ext_prov_pnlLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(ext_prov_users_lbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ext_prov_pnlLayout.setVerticalGroup(
            ext_prov_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ext_prov_pnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(ext_prov_users_lbl)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jLabel4.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel4.setText("Numero utenti");

        email_pnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        email_pnl.setMaximumSize(new java.awt.Dimension(350, 80));
        email_pnl.setMinimumSize(new java.awt.Dimension(350, 80));
        email_pnl.setPreferredSize(new java.awt.Dimension(350, 80));

        jLabel5.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel5.setText("Utenti registrati con email");

        email_users_lbl.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 15)); // NOI18N
        email_users_lbl.setText("caricamento...");

        javax.swing.GroupLayout email_pnlLayout = new javax.swing.GroupLayout(email_pnl);
        email_pnl.setLayout(email_pnlLayout);
        email_pnlLayout.setHorizontalGroup(
            email_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, email_pnlLayout.createSequentialGroup()
                .addContainerGap(64, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(65, 65, 65))
            .addGroup(email_pnlLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(email_users_lbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        email_pnlLayout.setVerticalGroup(
            email_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(email_pnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(email_users_lbl)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel7.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel7.setText("Numero ricerche");

        avg_review_pnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        avg_review_pnl.setMaximumSize(new java.awt.Dimension(350, 80));
        avg_review_pnl.setMinimumSize(new java.awt.Dimension(350, 80));
        avg_review_pnl.setPreferredSize(new java.awt.Dimension(350, 80));

        avg_review_lbl.setFont(new java.awt.Font("Microsoft YaHei", 1, 15)); // NOI18N
        avg_review_lbl.setText("caricamento...");

        jLabel9.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel9.setText("Valutazione media delle recensioni");

        javax.swing.GroupLayout avg_review_pnlLayout = new javax.swing.GroupLayout(avg_review_pnl);
        avg_review_pnl.setLayout(avg_review_pnlLayout);
        avg_review_pnlLayout.setHorizontalGroup(
            avg_review_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avg_review_pnlLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avg_review_pnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(avg_review_lbl)
                .addGap(119, 119, 119))
        );
        avg_review_pnlLayout.setVerticalGroup(
            avg_review_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avg_review_pnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(avg_review_lbl)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        users_searces_pnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        users_searces_pnl.setMaximumSize(new java.awt.Dimension(350, 80));
        users_searces_pnl.setMinimumSize(new java.awt.Dimension(350, 80));

        user_searches_lbl.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 15)); // NOI18N
        user_searches_lbl.setText("caricamento...");

        jLabel13.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel13.setText("Numero di ricerche di utenti");

        javax.swing.GroupLayout users_searces_pnlLayout = new javax.swing.GroupLayout(users_searces_pnl);
        users_searces_pnl.setLayout(users_searces_pnlLayout);
        users_searces_pnlLayout.setHorizontalGroup(
            users_searces_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, users_searces_pnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel13)
                .addGap(50, 50, 50))
            .addGroup(users_searces_pnlLayout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(user_searches_lbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        users_searces_pnlLayout.setVerticalGroup(
            users_searces_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, users_searces_pnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(user_searches_lbl)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jLabel14.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel14.setText("Recensioni");

        review_pnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        review_pnl.setMaximumSize(new java.awt.Dimension(350, 80));
        review_pnl.setMinimumSize(new java.awt.Dimension(350, 80));

        review_lbl.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 15)); // NOI18N
        review_lbl.setText("caricamento...");

        jLabel16.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel16.setText("Numero di recensioni");

        javax.swing.GroupLayout review_pnlLayout = new javax.swing.GroupLayout(review_pnl);
        review_pnl.setLayout(review_pnlLayout);
        review_pnlLayout.setHorizontalGroup(
            review_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(review_pnlLayout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, review_pnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(review_lbl)
                .addGap(119, 119, 119))
        );
        review_pnlLayout.setVerticalGroup(
            review_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, review_pnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(review_lbl)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        movie_searches_pnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        movie_searches_pnl.setMaximumSize(new java.awt.Dimension(350, 80));
        movie_searches_pnl.setMinimumSize(new java.awt.Dimension(350, 80));
        movie_searches_pnl.setPreferredSize(new java.awt.Dimension(350, 80));

        movie_searches_lbl.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 15)); // NOI18N
        movie_searches_lbl.setText("caricamento...");

        jLabel18.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel18.setText("Numero di ricerche di film");

        javax.swing.GroupLayout movie_searches_pnlLayout = new javax.swing.GroupLayout(movie_searches_pnl);
        movie_searches_pnl.setLayout(movie_searches_pnlLayout);
        movie_searches_pnlLayout.setHorizontalGroup(
            movie_searches_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(movie_searches_pnlLayout.createSequentialGroup()
                .addGroup(movie_searches_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(movie_searches_pnlLayout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jLabel18))
                    .addGroup(movie_searches_pnlLayout.createSequentialGroup()
                        .addGap(117, 117, 117)
                        .addComponent(movie_searches_lbl)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        movie_searches_pnlLayout.setVerticalGroup(
            movie_searches_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, movie_searches_pnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(movie_searches_lbl)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel19.setFont(new java.awt.Font("Microsoft Sans Serif", 0, 18)); // NOI18N
        jLabel19.setText("Liste di film");

        accesses_pnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        accesses_pnl.setMaximumSize(new java.awt.Dimension(350, 80));
        accesses_pnl.setMinimumSize(new java.awt.Dimension(350, 80));
        accesses_pnl.setName(""); // NOI18N
        accesses_pnl.setPreferredSize(new java.awt.Dimension(350, 80));

        accesses_lbl.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 15)); // NOI18N
        accesses_lbl.setText("caricamento...");

        jLabel21.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel21.setText("Numero di accessi");

        javax.swing.GroupLayout accesses_pnlLayout = new javax.swing.GroupLayout(accesses_pnl);
        accesses_pnl.setLayout(accesses_pnlLayout);
        accesses_pnlLayout.setHorizontalGroup(
            accesses_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(accesses_pnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(accesses_lbl)
                .addGap(119, 119, 119))
            .addGroup(accesses_pnlLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addComponent(jLabel21)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        accesses_pnlLayout.setVerticalGroup(
            accesses_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, accesses_pnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(accesses_lbl)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        avg_movie_pnl.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        avg_movie_pnl.setMaximumSize(new java.awt.Dimension(350, 80));
        avg_movie_pnl.setMinimumSize(new java.awt.Dimension(350, 80));
        avg_movie_pnl.setPreferredSize(new java.awt.Dimension(350, 80));

        avg_movie_lbl.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 15)); // NOI18N
        avg_movie_lbl.setText("caricamento...");

        jLabel22.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel22.setText("Numero medio di film nelle liste");

        javax.swing.GroupLayout avg_movie_pnlLayout = new javax.swing.GroupLayout(avg_movie_pnl);
        avg_movie_pnl.setLayout(avg_movie_pnlLayout);
        avg_movie_pnlLayout.setHorizontalGroup(
            avg_movie_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(avg_movie_pnlLayout.createSequentialGroup()
                .addGap(116, 116, 116)
                .addComponent(avg_movie_lbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avg_movie_pnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(27, 27, 27))
        );
        avg_movie_pnlLayout.setVerticalGroup(
            avg_movie_pnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, avg_movie_pnlLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(avg_movie_lbl)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        list_panel.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        list_panel.setMaximumSize(new java.awt.Dimension(350, 80));
        list_panel.setMinimumSize(new java.awt.Dimension(350, 80));

        list_lbl.setFont(new java.awt.Font("Microsoft YaHei UI", 1, 15)); // NOI18N
        list_lbl.setText("caricamento...");

        jLabel25.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        jLabel25.setText("Numero di liste");

        javax.swing.GroupLayout list_panelLayout = new javax.swing.GroupLayout(list_panel);
        list_panel.setLayout(list_panelLayout);
        list_panelLayout.setHorizontalGroup(
            list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, list_panelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(list_panelLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(list_lbl))
                    .addComponent(jLabel25))
                .addGap(105, 105, 105))
        );
        list_panelLayout.setVerticalGroup(
            list_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, list_panelLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(list_lbl)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout StatsPanelLayout = new javax.swing.GroupLayout(StatsPanel);
        StatsPanel.setLayout(StatsPanelLayout);
        StatsPanelLayout.setHorizontalGroup(
            StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StatsPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(ext_prov_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(accesses_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(users_searces_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(review_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(list_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(81, 81, 81)
                .addGroup(StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(email_pnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(avg_review_pnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(movie_searches_pnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(avg_movie_pnl, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(631, 631, 631))
            .addGroup(StatsPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7)
                    .addComponent(jLabel14)
                    .addComponent(jLabel19))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        StatsPanelLayout.setVerticalGroup(
            StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StatsPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(email_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ext_prov_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(movie_searches_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(users_searces_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(jLabel14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avg_review_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(review_pnl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(StatsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(avg_movie_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(list_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(accesses_pnl, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );

        PnlCards.add(StatsPanel, "StatsPanel");

        jSplitPane1.setRightComponent(PnlCards);

        NavigationBarMenu.setBackground(new java.awt.Color(0, 0, 0));
        NavigationBarMenu.setForeground(new java.awt.Color(255, 255, 255));
        NavigationBarMenu.setMaximumSize(new java.awt.Dimension(2000, 5620));
        NavigationBarMenu.setMinimumSize(new java.awt.Dimension(250, 562));
        NavigationBarMenu.setPreferredSize(new java.awt.Dimension(250, 700));

        CineMatesTitle.setFont(new java.awt.Font("Arial Rounded MT Bold", 1, 24)); // NOI18N
        CineMatesTitle.setForeground(new java.awt.Color(255, 255, 255));
        CineMatesTitle.setText("CineMates20");

        logged_operator_label.setFont(new java.awt.Font("Arial Rounded MT Bold", 2, 14)); // NOI18N
        logged_operator_label.setForeground(new java.awt.Color(255, 102, 102));
        logged_operator_label.setText("logged_operator");

        homePnl.setBackground(new java.awt.Color(0, 0, 0));
        homePnl.setAlignmentX(0.0F);
        homePnl.setAlignmentY(0.0F);
        homePnl.setPreferredSize(new java.awt.Dimension(0, 50));
        homePnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePnlMouseClicked(evt);
            }
        });

        home_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/home_icon_ok.png"))); // NOI18N

        home_lbl.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        home_lbl.setForeground(new java.awt.Color(255, 255, 255));
        home_lbl.setText("Home");

        javax.swing.GroupLayout homePnlLayout = new javax.swing.GroupLayout(homePnl);
        homePnl.setLayout(homePnlLayout);
        homePnlLayout.setHorizontalGroup(
            homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePnlLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(home_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(home_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(104, Short.MAX_VALUE))
        );
        homePnlLayout.setVerticalGroup(
            homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePnlLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(homePnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(home_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(home_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(10, Short.MAX_VALUE))
        );

        statsPnl.setBackground(new java.awt.Color(0, 0, 0));
        statsPnl.setAlignmentX(0.0F);
        statsPnl.setAlignmentY(0.0F);
        statsPnl.setMinimumSize(new java.awt.Dimension(100, 100));
        statsPnl.setPreferredSize(new java.awt.Dimension(0, 50));
        statsPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                statsPnlMouseClicked(evt);
            }
        });

        stats_lbl.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        stats_lbl.setForeground(new java.awt.Color(255, 255, 255));
        stats_lbl.setText("Statistiche");

        stats_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/stats_icon_ok.png"))); // NOI18N

        javax.swing.GroupLayout statsPnlLayout = new javax.swing.GroupLayout(statsPnl);
        statsPnl.setLayout(statsPnlLayout);
        statsPnlLayout.setHorizontalGroup(
            statsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(statsPnlLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(stats_icon)
                .addGap(18, 18, 18)
                .addComponent(stats_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );
        statsPnlLayout.setVerticalGroup(
            statsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, statsPnlLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(statsPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(stats_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stats_lbl))
                .addGap(13, 13, 13))
        );

        logoutPnl.setBackground(new java.awt.Color(0, 0, 0));
        logoutPnl.setPreferredSize(new java.awt.Dimension(150, 50));
        logoutPnl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutPanelMouseClicked(evt);
            }
        });

        logout_lbl.setFont(new java.awt.Font("Microsoft YaHei", 0, 18)); // NOI18N
        logout_lbl.setForeground(new java.awt.Color(255, 255, 255));
        logout_lbl.setText("Logout");

        logout_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout_icon_ok.png"))); // NOI18N

        javax.swing.GroupLayout logoutPnlLayout = new javax.swing.GroupLayout(logoutPnl);
        logoutPnl.setLayout(logoutPnlLayout);
        logoutPnlLayout.setHorizontalGroup(
            logoutPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPnlLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(logout_icon, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(logout_lbl)
                .addContainerGap(102, Short.MAX_VALUE))
        );
        logoutPnlLayout.setVerticalGroup(
            logoutPnlLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(logoutPnlLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(logout_lbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(logout_icon, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/operator_icon_ok.png"))); // NOI18N

        javax.swing.GroupLayout NavigationBarMenuLayout = new javax.swing.GroupLayout(NavigationBarMenu);
        NavigationBarMenu.setLayout(NavigationBarMenuLayout);
        NavigationBarMenuLayout.setHorizontalGroup(
            NavigationBarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, NavigationBarMenuLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(statsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(NavigationBarMenuLayout.createSequentialGroup()
                .addGroup(NavigationBarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(logoutPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(homePnl, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NavigationBarMenuLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(NavigationBarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(CineMatesTitle)
                            .addGroup(NavigationBarMenuLayout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(logged_operator_label, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        NavigationBarMenuLayout.setVerticalGroup(
            NavigationBarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NavigationBarMenuLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(CineMatesTitle)
                .addGap(48, 48, 48)
                .addGroup(NavigationBarMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(logged_operator_label))
                .addGap(87, 87, 87)
                .addComponent(homePnl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(statsPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(310, 310, 310)
                .addComponent(logoutPnl, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jSplitPane1.setLeftComponent(NavigationBarMenu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homePnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePnlMouseClicked
        card_layout.show(PnlCards,"HomePanel");
        homePnl.setBackground(Color.darkGray);
        statsPnl.setBackground(Color.black);
    }//GEN-LAST:event_homePnlMouseClicked

    private void statsPnlMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_statsPnlMouseClicked
        statsPnl.setBackground(Color.darkGray);
        homePnl.setBackground(Color.black);
        card_layout.show(PnlCards, "StatsPanel");
        System.out.println("vuoi vedere le statistiche e \" recovered stats \" è "+recovered_stats);
        
        if(recovered_stats==false){
            System.out.println("Te le mostro:");
            recovered_stats=true;
            controller.takeSystemStats();
        }
    }//GEN-LAST:event_statsPnlMouseClicked

    private void logoutPanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutPanelMouseClicked
        controller.logoutPressed();
    }//GEN-LAST:event_logoutPanelMouseClicked
    
    /*
    stats
    0: accesses; 1: ext_prov_users; 2: email_users; 3: users_searches; 4:movies_searches;
    5: reviews; 6: avg_rating_review; 7: lists; 8:avg_number_of_movies
    */
    private void blinkLabel(javax.swing.JLabel label, float[] stats, int index){
        if(showed_stats[index]>stats[index])
            label.setForeground(Color.red.darker());
        else if(showed_stats[index]<stats[index])
            label.setForeground(Color.green.darker());
        try {
            sleep(1100);
        } catch (InterruptedException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        label.setForeground(Color.black);
    }
    
    private void setStat(javax.swing.JLabel label, float[] stats, int index){
        if(index!=6 && index!=8)
            label.setText(String.valueOf((int)stats[index]));
        else
            label.setText(String.format("%.2f", stats[index]));
        blinkLabel(label,stats, index);
        showed_stats[index]=stats[index];
    }
    
    public void showStatsPanel(float[] stats){
	List<Thread> threads=new ArrayList<>(stats.length);
	System.out.println("---invocato showStatsPanel---");
	if(showed_stats[0]!=stats[0] || showed_stats[0]==0){
            //aggiorno numero di accessi 
            Thread t0=new Thread(()->{
                setStat(stats_labels[0],stats,0);
            });
            threads.add(t0);
            t0.start();
        }
	if(showed_stats[1]!=stats[1] || showed_stats[1]==0){
            //aggiorno numero di utenti registrati con provider esterno
            Thread t1=new Thread(()->{
                setStat(stats_labels[1],stats,1);
            });
            threads.add(t1);
            t1.start();
        }
	if(showed_stats[2]!=stats[2] || showed_stats[2]==0){
            //aggiorno numero di utenti registrati con email
            Thread t2=new Thread(()->{
                setStat(stats_labels[2],stats,2);
            });
            threads.add(t2);
            t2.start();
        }
	if(showed_stats[3]!=stats[3] || showed_stats[3]==0){
            //aggiorno il numero di ricerche di utenti
            Thread t3=new Thread(()->{
                setStat(stats_labels[3],stats,3);
            });
            threads.add(t3);
            t3.start();
        }
	if(showed_stats[4]!=stats[4] || showed_stats[4]==0){
            //aggiorno il numero di richerche di film
            Thread t4=new Thread(()->{
                setStat(stats_labels[4],stats,4);
            });
            threads.add(t4);
            t4.start();
        }
	if(showed_stats[5]!=stats[5] || showed_stats[5]==0){
            //aggiorno numero di recensioni nell'applicazione
            Thread t5=new Thread(()->{
                setStat(stats_labels[5],stats,5);
            });
            threads.add(t5);
            t5.start();
        }
	if(showed_stats[6]!=stats[6] || showed_stats[6]==0){
            //aggiorno valutazione media delle recensioni nell'applicazione
            Thread t6=new Thread(()->{
                setStat(stats_labels[6],stats,6);
            });
            threads.add(t6);
            t6.start();
        }
	if(showed_stats[7]!=stats[7] || showed_stats[7]==0){
            //aggiorno il numero di liste
            Thread t7=new Thread(()->{
                setStat(stats_labels[7],stats,7);
            });
            threads.add(t7);
            t7.start();
        }
	if(showed_stats[8]!=stats[8] || showed_stats[8]==0){
            //aggiorno il numero medio di film nelle liste
            Thread t8=new Thread(()->{
                setStat(stats_labels[8],stats,8);
            });
            threads.add(t8);
            t8.start();
        }
	for(Thread x:threads){
            try {
                x.join();
            } catch (InterruptedException ex) {
                Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    public CardLayout getCard_layout() {
        return card_layout;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CineMatesTitle;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel NavigationBarMenu;
    private javax.swing.JPanel PnlCards;
    private javax.swing.JPanel StatsPanel;
    private javax.swing.JLabel accesses_lbl;
    private javax.swing.JPanel accesses_pnl;
    private javax.swing.JLabel avg_movie_lbl;
    private javax.swing.JPanel avg_movie_pnl;
    private javax.swing.JLabel avg_review_lbl;
    private javax.swing.JPanel avg_review_pnl;
    private javax.swing.JPanel email_pnl;
    private javax.swing.JLabel email_users_lbl;
    private javax.swing.JPanel ext_prov_pnl;
    private javax.swing.JLabel ext_prov_users_lbl;
    private javax.swing.JPanel homePnl;
    private javax.swing.JLabel home_icon;
    private javax.swing.JLabel home_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel list_lbl;
    private javax.swing.JPanel list_panel;
    private javax.swing.JLabel logged_operator_label;
    private javax.swing.JPanel logoutPnl;
    private javax.swing.JLabel logout_icon;
    private javax.swing.JLabel logout_lbl;
    private javax.swing.JLabel movie_searches_lbl;
    private javax.swing.JPanel movie_searches_pnl;
    private javax.swing.JLabel review_lbl;
    private javax.swing.JPanel review_pnl;
    private javax.swing.JPanel statsPnl;
    private javax.swing.JLabel stats_icon;
    private javax.swing.JLabel stats_lbl;
    private javax.swing.JLabel user_searches_lbl;
    private javax.swing.JPanel users_searces_pnl;
    // End of variables declaration//GEN-END:variables
}
